### ISSUE TITLE
I am getting an empty page when I visit the site

### ISSUE THREAD

**Issue by amitu** [rustindia/rustindia.github.io#6]
When I visit https://rustindia.github.io I ge this:

![4CE3A2BE-3AA3-4C20-B10C-1C24C17FEEF2](https://user-images.githubusercontent.com/58662/120913445-e26ae000-c6b4-11eb-83ad-919a2234be29.png)

Is this expected?

Can we use mdbook instead of the React component?

**Comment by ranjithrajv** [comment]
It's fixed now, with a new page deployed. All thanks to @me-diru
